<template>
    <div style="width: 100%; ">
        <Button :disabled="!changes" :severity="changes ? 'primary' : 'secondary'"  style="position: absolute; bottom: 10px; right: 20px;" @click="saveConfig"  label="Save changes"  />
        <div class="config-options">
            <span class="name-w-label">                
                <p>
                    Show download progress notification:
                </p>
                
                <p style="font-size: .9em;">
                    Detailed: Create a notification for each new download<br>
                    Summarized: Display only one notification, showing the progress to complete all downloads
                </p>
            </span>
            <div style="width: 100%;">
                <AutoComplete v-if="newUserConfig.interface" :forceSelection="true" fluid v-model="newUserConfig.interface.showDownloadProgressNotification" dropdown :suggestions="filteredNotificationOption" @complete="searchNotificationOption" />
                <Message style="margin-left: 1em;" v-if="(missingInfo && (newUserConfig.interface.showDownloadProgressNotification == null))" severity="error" size="small" variant="simple">Select a valid value</Message>
            </div>
        </div>
        <div class="config-options">
            <span>
                Notifications position:
            </span>
            <div style="width: 100%;">
                <AutoComplete v-if="newUserConfig.interface" :forceSelection="true" fluid v-model="newUserConfig.interface.notificationPosition" dropdown :suggestions="filteredNotificationPosition" @complete="searchNotificationPosition" />
                <Message style="margin-left: 1em;" v-if="(missingInfo && (newUserConfig.interface.notificationPosition == null))" severity="error" size="small" variant="simple">Select a valid value</Message>
            </div>
        </div>
    </div>

</template>
<script lang="ts">
import Button from 'primevue/button';
import { useFSStore } from '../../stores/fileSystem';
import { changeConfig, getEmptyUserConfig } from '../../helpers/userConfig';
import ytdlpVariables, { supportedLangs } from '../../constants/ytdlpVariables';
import AutoComplete from 'primevue/autocomplete';
import BaseFileInput from '../BaseFileInput.vue';
import { useUserConfig } from '../../stores/userConfig';
import FloatLabel from 'primevue/floatlabel';
import { audioExtensions, imageExtensions, videoExtensions } from '../../constants/fileExtensions';
import ToggleSwitch from 'primevue/toggleswitch';
import Message from 'primevue/message';

    export default {
        name: "TheHeader",
        components: {
            BaseFileInput,
            Button,
            AutoComplete,
            FloatLabel,
            ToggleSwitch,
            Message
        },
        data() {
            return {
                changes: false,
                userConfig: {} as UserConfig,
                newUserConfig: getEmptyUserConfig(),
                filteredNotificationOption:[] as string[],
                filteredNotificationPosition:[] as string[],
                notificationOptions: [] as YTDLPOption[],
                notificationPosition: [] as YTDLPOption[],
                subtitlesTypes: [
                    {
                        name: "Autogenerated",
                        code: "auto"
                    },
                    {
                        name: "Normal",
                        code: "normal"
                    },
                    {
                        name: "Both",
                        code: "both"
                    },
                ] as YTDLPOption[],
                missingInfo: false,
            }
        },
        setup() {
            const fsStore = useFSStore()
            const userConfigStore = useUserConfig();
            const changeUserConfig = (config: keyof UserConfig, value: UserConfig[keyof UserConfig]) => changeConfig(config,value);

            return {
                changeUserConfig,
                fsStore,
                userConfigStore
            }
        },
        watch: {
            newUserConfig: {
                handler: function(val) {
                    this.changes = this.compareUserConfigs(this.userConfig, val);
                },
                deep: true
            }
        },
        mounted() {
            this.notificationOptions = [//!Refactor: All possible types of interface.showDownloadProgressNotification of user
                {name: "Disabled", code:'disabled'},
                {name: "Detailed", code:'detailed'},
                {name: "Summarized", code:'summarized'},
            ]
            this.notificationPosition = [ //!Refactor: All possible types of interface.notificationPosition of user
                {name:"center" , code: "center" },
                {name:"top-left", code: "top-left"},
                {name:"top-center", code: "top-center"},
                {name:"top-right", code: "top-right"},
                {name:"bottom-left", code: "bottom-left"},
                {name:"bottom-center", code: "bottom-center"},
                {name:"bottom-right", code: "bottom-right"}
            ]
            this.userConfigStore.$subscribe((userConfig) => {
                //@ts-ignore
                this.userConfig = JSON.parse(JSON.stringify(userConfig.events.target.userConfig)); 
                this.newUserConfig = JSON.parse(JSON.stringify(this.userConfig));
            });

            this.userConfig = JSON.parse(JSON.stringify(this.userConfigStore.getUserConfig)); //guarantee that is a completely new object with cloned information
            this.newUserConfig = JSON.parse(JSON.stringify(this.userConfig));
        },
        methods: {
            checkInputsCompleted():boolean {
                if(this.newUserConfig.interface.notificationPosition == null ||
                this.newUserConfig.interface.showDownloadProgressNotification == null 
                ){
                    console.log(this.newUserConfig)
                    return false
                }
                console.log(this.newUserConfig)
                return true
            },
            searchNotificationOption(event:any) {
                this.filteredNotificationOption = event.query ? this.notificationOptions.filter((item) => {
                    return item.name.toLowerCase().includes(event.query.toLowerCase());
                }).map((item)=>item.name): this.notificationOptions.map((item)=>item.name);
            },
            searchNotificationPosition(event:any) {
                this.filteredNotificationPosition = event.query ? this.notificationPosition.filter((item) => {
                    return item.name.toLowerCase().includes(event.query.toLowerCase());
                }).map((item)=>item.name): this.notificationPosition.map((item)=>item.name);
            },
            compareUserConfigs(obj1: UserConfig, obj2:UserConfig) {
                const keys1 = Object.keys(obj1);
                const keys2 = Object.keys(obj2);

                if (keys1.length !== keys2.length) {
                    console.log("Length different");
                    return true; 
                }

                for (let key of keys1) {
                    if (!keys2.includes(key) || JSON.stringify(obj1[key as keyof UserConfig]) != JSON.stringify(obj2[key as keyof UserConfig])) {
                        console.log(key);
                        return true; 
                    }
                }

                return false;
            },
            async saveConfig() {
                if(this.checkInputsCompleted()) {
                    if(this.changes) {
                        this.userConfigStore.setUserConfig(this.newUserConfig);
                        this.$emit('setConfigModalVisible', false);
                    }
                    this.missingInfo = false;
                } else {
                    this.newNotification("Missing user information",3000);
                    this.missingInfo = true;
                }
            },
            newNotification(message: string, life: number) {
                this.$toast.add({
                    severity: 'secondary',
                    summary: 'Alert',
                    detail: message,
                    life: life,
                    closable: true
                })
            }
        }
    }
</script>
<style scoped>
    .config-sidebar {
        border-right: 1px solid var(--surface-700);
        padding-right: 1.25rem;
        margin-right: 1em;
        display: flex;
        width: 25%;
        flex-direction: column;
        justify-content: space-between;
        align-items: center;
    }
        .config-sidebar button {
            margin: .2em 0;
        }

    .config-content {
        width: 100%;
        height: 100%;
        position: relative;
    }

        .config-options {
            display: flex;
            align-items: center;
            justify-content: space-between;
            margin-bottom: 3em;
        }
            .config-options span {
                margin-right: 1em;
                font-weight: 500;
            }

            .config-options .name-w-label {
                display: flex;
                flex-direction: column;
                align-items: start;
            }
            .config-options .name-w-label p:last-child {
                color: var(--surface-700);
            } 

    input {
        background: var(--black-background-900);
        border: 1px solid var(--black-background-800);
        border-radius: var(--p-form-field-border-radius);
        padding: .4em .9em;
        outline: none;
        transition: all ease .2s;
    }
        
        input:focus, input:hover {
            border-color: var(--black-background-700);
            transition: all ease .2s;
        }


</style>