<template>
    <div style="width: 100%; ">
        <Button :disabled="!changes" :severity="changes ? 'primary' : 'secondary'"  style="position: absolute; bottom: 10px; right: 20px;" @click="saveConfig"  label="Save changes"  />
        <div class="config-options">
            <span>
                Download thumbnail by default:
            </span>
            <AutoComplete v-if="newUserConfig.metadata" :forceSelection="true" fluid v-model="newUserConfig.metadata.downloadThumbnailByDefault" dropdown :suggestions="filteredImageExt" @complete="searchImageExt" />
        </div>
        <div class="config-options">
            <span>
                Download description in a .description file by default:
            </span>
            <div style="flex: 1; display: flex; align-items: center; justify-content: flex-end;">
                <ToggleSwitch v-if="newUserConfig.metadata" v-model="newUserConfig.metadata.downloadDescriptionInFileDefault" />
            </div>
        </div>
        <div class="config-options">
            <span>
                Download video annotations by default:
            </span>
            <div style="flex: 1; display: flex; align-items: center; justify-content: flex-end;">
                <ToggleSwitch v-if="newUserConfig.metadata" v-model="newUserConfig.metadata.downloadVideoAnnotations" />
            </div>
        </div>
        <div class="config-options">
            <span>
                Download Subtitles in a file by default:
            </span>
            <div style="flex: 1; display: flex; align-items: center; justify-content: flex-end;">
                <ToggleSwitch v-if="newUserConfig.metadata" v-model="newUserConfig.metadata.downloadSubtitlesInFile.enabled" />
            </div>
        </div>
        <div v-if="newUserConfig.metadata.downloadSubtitlesInFile.enabled" class="config-options" style="margin-top: -1em; padding-left: 1em;">
            <span>
                Subtitles type:
            </span>
            <div style="flex: 1; display: flex; align-items: center; justify-content: flex-end;">
                <AutoComplete v-if="newUserConfig.metadata" :forceSelection="true" fluid v-model="newUserConfig.metadata.downloadSubtitlesInFile.type" dropdown :suggestions="filteredSubTypes" @complete="searchSubTypes" />
            </div>
        </div>
        <div v-if="newUserConfig.metadata.downloadSubtitlesInFile.enabled" class="config-options" style="margin-top: -1em; padding-left: 1em;">
            <span>
                Subtitles language:
            </span>
            <div style="flex: 1; display: flex; align-items: center; justify-content: flex-end;">
                <AutoComplete v-if="newUserConfig.metadata" :forceSelection="true" fluid v-model="newUserConfig.metadata.downloadSubtitlesInFile.lang" dropdown :suggestions="filteredLangs" @complete="searchSupportedLangs" />
            </div>
        </div>
    </div>

</template>
<script lang="ts">
import Button from 'primevue/button';
import { useFSStore } from '../../stores/fileSystem';
import { changeConfig, getEmptyUserConfig } from '../../helpers/userConfig';
import ytdlpVariables, { supportedLangs } from '../../constants/ytdlpVariables';
import AutoComplete from 'primevue/autocomplete';
import BaseFileInput from '../BaseFileInput.vue';
import { useUserConfig } from '../../stores/userConfig';
import FloatLabel from 'primevue/floatlabel';
import { audioExtensions, imageExtensions, videoExtensions } from '../../constants/fileExtensions';
import ToggleSwitch from 'primevue/toggleswitch';

    export default {
        name: "TheHeader",
        components: {
            BaseFileInput,
            Button,
            AutoComplete,
            FloatLabel,
            ToggleSwitch
        },
        data() {
            return {
                changes: false,
                userConfig: {} as UserConfig,
                newUserConfig: getEmptyUserConfig(),
                filteredImageExt:[] as string[],
                filteredLangs:[] as string[],
                filteredSubTypes:[] as string[],
                thumbnailByDefaultOptions: [] as YTDLPOption[],
                subtitlesTypes: [
                    {
                        name: "Autogenerated",
                        code: "auto"
                    },
                    {
                        name: "Normal",
                        code: "normal"
                    },
                    {
                        name: "Both",
                        code: "both"
                    },
                ] as YTDLPOption[]
            }
        },
        setup() {
            const fsStore = useFSStore()
            const userConfigStore = useUserConfig();
            const changeUserConfig = (config: keyof UserConfig, value: UserConfig[keyof UserConfig]) => changeConfig(config,value);

            return {
                changeUserConfig,
                fsStore,
                userConfigStore
            }
        },
        watch: {
            newUserConfig: {
                handler: function(val) {
                    this.changes = this.compareUserConfigs(this.userConfig, val);
                },
                deep: true
            }
        },
        mounted() {
            this.thumbnailByDefaultOptions = [{
                name : "Disabled",
                code : ''
            },...imageExtensions]
            this.userConfigStore.$subscribe((userConfig) => {
                //@ts-ignore
                this.userConfig = JSON.parse(JSON.stringify(userConfig.events.target.userConfig)); 
                this.newUserConfig = JSON.parse(JSON.stringify(this.userConfig));
            });

            this.userConfig = JSON.parse(JSON.stringify(this.userConfigStore.getUserConfig)); //guarantee that is a completely new object with cloned information
            this.newUserConfig = JSON.parse(JSON.stringify(this.userConfig));
        },
        methods: {
            searchImageExt(event:any) {
                this.filteredImageExt = event.query ? this.thumbnailByDefaultOptions.filter((item) => {
                    return item.name.toLowerCase().includes(event.query.toLowerCase());
                }).map((item)=>item.name): this.thumbnailByDefaultOptions.map((item)=>item.name);
            },
            searchSupportedLangs(event:any) {
                this.filteredLangs = event.query ? supportedLangs.filter((item) => {
                    return item.name.toLowerCase().includes(event.query.toLowerCase());
                }).map((item)=>item.name): supportedLangs.map((item)=>item.name);
            },
            searchSubTypes(event:any) {
                this.filteredSubTypes = event.query ? this.subtitlesTypes.filter((item) => {
                    return item.name.toLowerCase().includes(event.query.toLowerCase());
                }).map((item)=>item.name): this.subtitlesTypes.map((item)=>item.name);
            },
            compareUserConfigs(obj1: UserConfig, obj2:UserConfig) {
                const keys1 = Object.keys(obj1);
                const keys2 = Object.keys(obj2);

                if (keys1.length !== keys2.length) {
                    console.log("Length different");
                    return true; 
                }

                for (let key of keys1) {
                    if (!keys2.includes(key) || JSON.stringify(obj1[key as keyof UserConfig]) != JSON.stringify(obj2[key as keyof UserConfig])) {
                        console.log(key);
                        return true; 
                    }
                }

                return false;
            },
            async saveConfig() {
                if(this.changes) {
                    this.userConfigStore.setUserConfig(this.newUserConfig);
                    this.$emit('setConfigModalVisible', false);
                }
            },
        }
    }
</script>
<style scoped>
    .config-sidebar {
        border-right: 1px solid var(--surface-700);
        padding-right: 1.25rem;
        margin-right: 1em;
        display: flex;
        width: 25%;
        flex-direction: column;
        justify-content: space-between;
        align-items: center;
    }
        .config-sidebar button {
            margin: .2em 0;
        }

    .config-content {
        width: 100%;
        height: 100%;
        position: relative;
    }

        .config-options {
            display: flex;
            align-items: center;
            justify-content: space-between;
            margin-bottom: 3em;
        }
            .config-options span {
                margin-right: 1em;
                font-weight: 500;
            }

            .config-options .name-w-label {
                display: flex;
                flex-direction: column;
                align-items: start;
            }
            .config-options .name-w-label p:last-child {
                color: var(--surface-700);
            } 

    input {
        background: var(--black-background-900);
        border: 1px solid var(--black-background-800);
        border-radius: var(--p-form-field-border-radius);
        padding: .4em .9em;
        outline: none;
        transition: all ease .2s;
    }
        
        input:focus, input:hover {
            border-color: var(--black-background-700);
            transition: all ease .2s;
        }


</style>