name: Bug Report
description: File a bug report
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: 'I have checked the following:'
      options:
        - label: I've searched existing issues and found nothing related to my issue.
          required: true
  - type: textarea
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of the bug."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to reproduce the error"
      description: "Describe by steps how this bug occurs."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Screenshots/Video"
      description: "Add some screenshots and videos to help explain the problem."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Device information"
      description: "Add the device information: OS, Version."
    validations:
      required: true
